version: '3.8'

services:
  rag-import:
    container_name: rag-import
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "app.import_process.api.file_import_service"]
    ports:
      - "8002:8000"
    volumes:
      - /opt/rag/models:/app/models:ro
      - ./output:/app/output
      - ./logs/import:/app/logs
    env_file:
      - .env

  rag-query:
    container_name: rag-query
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "app.query_process.api.query_service"]
    ports:
      - "8001:8001"
    volumes:
      - /opt/rag/models:/app/models:ro
      - ./logs/query:/app/logs
    env_file:
      - .env
    restart: on-failure
